using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Dynamic.Core;
using Diamond.DataSource.Extensions;
using ERP.Data.Utilities;
using ERP.Services.Bases;

namespace ERP.Services.Search
{
    public class NBSCCReportService : SearchService
    {
        private Services.Entities.NBSCCReportService NBSCCReport { get; }
        private Services.Business.Entities.POItemService POItem { get; }
        private Services.Entities.POService PO { get; }
        private Services.Entities.VendorService Vendor { get; }
        public NBSCCReportService(
            Services.Entities.NBSCCReportService nbSCCReportService,
            Services.Business.Entities.POItemService poItemService,
            Services.Entities.POService poService,
            Services.Entities.VendorService vendorService,
            UnitOfWork unitOfWork) : base(unitOfWork)
        {
            NBSCCReport = nbSCCReportService;
            POItem = poItemService;
            PO = poService;
            Vendor = vendorService;
        }

        public IQueryable<Models.Views.NBSCCReport> Get(string predicate)
        {
            var result = (
                from r in NBSCCReport.Get()
                join pi in POItem.Get() on new { POItemId = r.POItemId, POItemLocaleId = r.POItemLocaleId } equals new { POItemId = (decimal?)pi.Id, POItemLocaleId = (decimal?)pi.LocaleId }
                select new
                {
                    Id = r.Id,
                    LocaleId = r.LocaleId,
                    POItemId = r.POItemId,
                    POItemLocaleId = r.POItemLocaleId,
                    ModifyUserName = r.ModifyUserName,
                    LastUpdateTime = r.LastUpdateTime,
                    PONo = r.PONo,
                    Status = r.Status,
                    POStatus = r.POStatus,
                    POType = r.POType,
                    OrderType = r.OrderType,
                    PDate = r.PODate.Substring(6,4)+r.PODate.Substring(3,2)+r.PODate.Substring(0,2),
                    PODate = r.PODate,
                    Season = r.Season,
                    FreightTerms = r.FreightTerms,
                    PaymentTerms = r.PaymentTerms,
                    PaymentMethod = r.PaymentMethod,
                    Via = r.Via,
                    BuyerCode = r.BuyerCode,
                    BuyerName = r.BuyerName,
                    VendorCode = r.VendorCode,
                    VendorName = r.VendorName,
                    FactoryCode = r.FactoryCode,
                    FactoryAddress1 = r.FactoryAddress1,
                    FactoryAddress2 = r.FactoryAddress2,
                    FactoryAddress3 = r.FactoryAddress3,
                    FactoryAddress4 = r.FactoryAddress4,
                    FactoryPhone = r.FactoryPhone,
                    FactoryFax = r.FactoryFax,
                    BillToCompanyName = r.BillToCompanyName,
                    BillToAddress1 = r.BillToAddress1,
                    BillToAddress2 = r.BillToAddress2,
                    BillToAddress3 = r.BillToAddress3,
                    BillToAddress4 = r.BillToAddress4,
                    BillToPhone = r.BillToPhone,
                    BillToFax = r.BillToFax,
                    ConsigneeCompanyName = r.ConsigneeCompanyName,
                    ConsigneeAddress1 = r.ConsigneeAddress1,
                    ConsigneeAddress2 = r.ConsigneeAddress2,
                    ConsigneeAddress3 = r.ConsigneeAddress3,
                    ConsigneeAddress4 = r.ConsigneeAddress4,
                    ConsigneePhone = r.ConsigneePhone,
                    ConsigneeFax = r.ConsigneeFax,
                    AgentCompanyName = r.AgentCompanyName,
                    AgentAddress1 = r.AgentAddress1,
                    AgentAddress2 = r.AgentAddress2,
                    AgentAddress3 = r.AgentAddress3,
                    AgentAddress4 = r.AgentAddress4,
                    AgentPhone = r.AgentPhone,
                    AgentFax = r.AgentFax,
                    AgentAttn = r.AgentAttn,
                    ShipToCompanyName = r.ShipToCompanyName,
                    ShipToAddress1 = r.ShipToAddress1,
                    ShipToAddress2 = r.ShipToAddress2,
                    ShipToAddress3 = r.ShipToAddress3,
                    ShipToAddress4 = r.ShipToAddress4,
                    ShipToPhone = r.ShipToPhone,
                    ShipToFax = r.ShipToFax,
                    ShipFromLocation = r.ShipFromLocation,
                    NotifyPartyCompanyName = r.NotifyPartyCompanyName,
                    NotifyPartyAddress1 = r.NotifyPartyAddress1,
                    NotifyPartyAddress2 = r.NotifyPartyAddress2,
                    NotifyPartyAddress3 = r.NotifyPartyAddress3,
                    NotifyPartyAddress4 = r.NotifyPartyAddress4,
                    NotifyPartyPhone = r.NotifyPartyPhone,
                    NotifyPartyFax = r.NotifyPartyFax,
                    NotifyPartyAttn = r.NotifyPartyAttn,
                    NBPartNo = r.NBPartNo,
                    NBColorKey = r.NBColorKey,
                    SupplierLineItemNo = r.SupplierLineItemNo,
                    SupplierMaterialNo = r.SupplierMaterialNo,
                    NBMaterialDescription = r.NBMaterialDescription,
                    SupplierMaterialDescription = r.SupplierMaterialDescription,
                    UOM = r.UOM,
                    Quantity = r.Quantity,
                    Length = r.Length,
                    RXFD = r.RXFD,
                    RETA = r.RETA,
                    ShipMode = r.ShipMode,
                    PackType = r.PackType,
                    SpecialTreatment = r.SpecialTreatment,
                    AdditionInstruction = r.AdditionInstruction,
                    StyleNo = r.StyleNo,
                    CustomerPONo = r.CustomerPONo,
                    ReceiptQuantity = r.ReceiptQuantity,
                    ReceiptDate = r.ReceiptDate,
                    ReceiptQuantityQC = r.ReceiptQuantityQC,
                    RejectedQuantity = r.RejectedQuantity,
                    RejectQuantityForColorIssues = r.RejectQuantityForColorIssues,
                    RejectQuantityForCosmeticIssues = r.RejectQuantityForCosmeticIssues,
                    ResolvedQuantity = r.ResolvedQuantity,
                    ResolvedDate = r.ResolvedDate,
                    FactoryPOPrintFileName = r.FactoryPOPrintFileName,
                    SupplieRemark = r.SupplieRemark,
                    FactoryRemark = r.FactoryRemark,
                    Vendor = pi.VendorId,
                    MaterialName = pi.Material,
                    MaterialId = pi.MaterialId
                }
            )
            .Where(new ParsingConfig { CustomTypeProvider = new DynamicLinqProvider() }, predicate)
            .Select(i => new ERP.Models.Views.NBSCCReport
            {
                Id = i.Id,
                LocaleId = i.LocaleId,
                POItemId = i.POItemId,
                POItemLocaleId = i.POItemLocaleId,
                ModifyUserName = i.ModifyUserName,
                LastUpdateTime = i.LastUpdateTime,
                PONo = i.PONo,
                Status = i.Status,
                POStatus = i.POStatus,
                POType = i.POType,
                OrderType = i.OrderType,
                PODate = i.PDate,
                Season = i.Season,
                FreightTerms = i.FreightTerms,
                PaymentTerms = i.PaymentTerms,
                PaymentMethod = i.PaymentMethod,
                Via = i.Via,
                BuyerCode = i.BuyerCode,
                BuyerName = i.BuyerName,
                VendorCode = i.VendorCode,
                VendorName = i.VendorName,
                FactoryCode = i.FactoryCode,
                FactoryAddress1 = i.FactoryAddress1,
                FactoryAddress2 = i.FactoryAddress2,
                FactoryAddress3 = i.FactoryAddress3,
                FactoryAddress4 = i.FactoryAddress4,
                FactoryPhone = i.FactoryPhone,
                FactoryFax = i.FactoryFax,
                BillToCompanyName = i.BillToCompanyName,
                BillToAddress1 = i.BillToAddress1,
                BillToAddress2 = i.BillToAddress2,
                BillToAddress3 = i.BillToAddress3,
                BillToAddress4 = i.BillToAddress4,
                BillToPhone = i.BillToPhone,
                BillToFax = i.BillToFax,
                ConsigneeCompanyName = i.ConsigneeCompanyName,
                ConsigneeAddress1 = i.ConsigneeAddress1,
                ConsigneeAddress2 = i.ConsigneeAddress2,
                ConsigneeAddress3 = i.ConsigneeAddress3,
                ConsigneeAddress4 = i.ConsigneeAddress4,
                ConsigneePhone = i.ConsigneePhone,
                ConsigneeFax = i.ConsigneeFax,
                AgentCompanyName = i.AgentCompanyName,
                AgentAddress1 = i.AgentAddress1,
                AgentAddress2 = i.AgentAddress2,
                AgentAddress3 = i.AgentAddress3,
                AgentAddress4 = i.AgentAddress4,
                AgentPhone = i.AgentPhone,
                AgentFax = i.AgentFax,
                AgentAttn = i.AgentAttn,
                ShipToCompanyName = i.ShipToCompanyName,
                ShipToAddress1 = i.ShipToAddress1,
                ShipToAddress2 = i.ShipToAddress2,
                ShipToAddress3 = i.ShipToAddress3,
                ShipToAddress4 = i.ShipToAddress4,
                ShipToPhone = i.ShipToPhone,
                ShipToFax = i.ShipToFax,
                ShipFromLocation = i.ShipFromLocation,
                NotifyPartyCompanyName = i.NotifyPartyCompanyName,
                NotifyPartyAddress1 = i.NotifyPartyAddress1,
                NotifyPartyAddress2 = i.NotifyPartyAddress2,
                NotifyPartyAddress3 = i.NotifyPartyAddress3,
                NotifyPartyAddress4 = i.NotifyPartyAddress4,
                NotifyPartyPhone = i.NotifyPartyPhone,
                NotifyPartyFax = i.NotifyPartyFax,
                NotifyPartyAttn = i.NotifyPartyAttn,
                NBPartNo = i.NBPartNo,
                NBColorKey = i.NBColorKey,
                SupplierLineItemNo = i.SupplierLineItemNo,
                SupplierMaterialNo = i.SupplierMaterialNo,
                NBMaterialDescription = i.NBMaterialDescription,
                SupplierMaterialDescription = i.SupplierMaterialDescription,
                UOM = i.UOM,
                Quantity = i.Quantity,
                Length = i.Length,
                RXFD = i.RXFD,
                RETA = i.RETA,
                ShipMode = i.ShipMode,
                PackType = i.PackType,
                SpecialTreatment = i.SpecialTreatment,
                AdditionInstruction = i.AdditionInstruction,
                StyleNo = i.StyleNo,
                CustomerPONo = i.CustomerPONo,
                ReceiptQuantity = i.ReceiptQuantity,
                ReceiptDate = i.ReceiptDate,
                ReceiptQuantityQC = i.ReceiptQuantityQC,
                RejectedQuantity = i.RejectedQuantity,
                RejectQuantityForColorIssues = i.RejectQuantityForColorIssues,
                RejectQuantityForCosmeticIssues = i.RejectQuantityForCosmeticIssues,
                ResolvedQuantity = i.ResolvedQuantity,
                ResolvedDate = i.ResolvedDate,
                FactoryPOPrintFileName = i.FactoryPOPrintFileName,
                SupplieRemark = i.SupplieRemark,
                FactoryRemark = i.FactoryRemark,
            })
            .Distinct();
            return result;
        }

    }
}